updated tr_tr
Brian-Wuest/MC-Prefab pull request #258
Opened 2022-02-13 13:04 UTC by Hexasan

+updated turkish language file

that old one was a mess, lowercase things that should be uppercase, things already translated in the base game that is translated differently here, other weird things, but I believe I fixed most of them

2022-02-13 13:06 UTC, Hexasan commented
netherite sickle was translated as "dutch sickle" in the old translation lmao

2022-02-13 15:06 UTC, Brian-Wuest requested changes

2022-02-13 15:06 UTC, Brian-Wuest commented on src/main/resources/assets/prefab/lang/tr_tr.json
> +    "item.prefab.item_bulldozer": "Yaratıcı Buldozer",
The bulldozer isn't just used in creative-mode. This should just translate from the English word of "Bulldozer"

2022-02-13 15:06 UTC, Brian-Wuest commented on src/main/resources/assets/prefab/lang/tr_tr.json
> +    "block.prefab.block_grass_slab": "Çimenli Toprak",
This translates to "Grassy Soil" and is used for both the Grass Slab and Grass Wall.

2022-02-13 15:06 UTC, Brian-Wuest commented on src/main/resources/assets/prefab/lang/tr_tr.json
> +    "prefab.gui.starter.style.label": "Zemin Blok Türü",
Why is this "Ground Block Type" when it's supposed to be "House Size""

2022-02-14 22:56 UTC, Brian-Wuest approved these changes

2022-02-14 22:59 UTC, merged